# Canvas Account Domain
canvasDomain: 'canvas.instructure.com'

# Canvas Account Developer Key Information
#   this is required to obtain user access tokens
developerKey:
  clientId: '<DEVELOPER_KEY_ID>'
  clientSecret: '<DEVELOPER_KEY_SECRET>'
  redirectUri: 'urn:ietf:wg:oauth:2.0:oob'

# Canvas Account Admin Access Token
accountAdmin:
  token: '<ACCOUNT_ADMIN_ACCESS_TOKEN>'
